yiisoft/actions

.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
README.md

Add phpbench.yml, fix minor corrections.

---

.github/workflows/psalm.yml

Add options --php-version to psalm.

---

.github/workflows/roave-infection.yml

Add ini-values to roave-infection.yml.

---

README.md

Add rector usage `README.md`

---

.github/workflows/composer-require-checker.yml
README.md

Add composer-require-checker.yml.

---

.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

Tests cache composer.

---

.github/workflows/phpunit.yml

Use codecov actions.

---

.github/workflows/roave-infection.yml

Fix options command cli.

---

.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

Add customizable `composer-command` input

---

.github/workflows/phpunit.yml

| Fixed issues  | -
For exmaple, it's need for full coverage [here](https://github.com/yiisoft/validator/pull/437)

Pass coverage from all PHP versions in `phpunit.yml`

---

.github/workflows/psalm.yml

Add config to psalm

---

.github/workflows/bc.yml

Add bc workflow.

---

.github/workflows/composer-require-checker.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml

Add PHP extensions to other workflows

---

.github/workflows/rector.yml
docs/rector.md

Example of usage: https://github.com/yiisoft/html/pull/163

Improve rector

---

.github/workflows/bc.yml
.github/workflows/codeception.yml
.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

tests in:
- `yiisoft/yii2`.
- `yiisoft/yi-db-migration`.

Add `concurrency` workflow.

---

.github/workflows/bc.yml
.github/workflows/codeception.yml
.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

Revert "Add `concurrency` workflow."

---

.github/workflows/bc.yml
.github/workflows/codeception.yml
.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

Revert "Update `actions/checkout@v4`."

---

.github/workflows/bc.yml
.github/workflows/codeception.yml
.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

Revert "Revert "Update `actions/checkout@v4`.""

---

.github/workflows/phpbench.yml

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Adjust phpbench workflow

---

.github/workflows/roave-infection.yml

Fix option `roave-infection.yml`.

---

.github/workflows/ecs.yml
docs/ecs.md

Add ecs workflow.

---

.github/workflows/codeception.yml

Add debug mode to `codeception`, download error files.

---

.github/workflows/codeception.yml

Allowed custom command codeception, and run power shell in windows.

---

.github/workflows/phpunit.yml

Update codecov to v4.

---

.github/workflows/codeception.yml
.github/workflows/phpunit.yml

Fix codecov action.

---

.github/workflows/roave-infection.yml

Use bin-name in roave-infection

---

.github/workflows/rector.yml

Improve rector.yml

---

.github/workflows/phpbench.yml

| Fixed issues  | ❌
Saves PhpBench baseline file and compares PR result to the given baseline

PhpBench action improvement

---

db/subpackage-install/action.yml

| Is bugfix?    | ✔️/❌
| Fixed issues  |

Add "as version" for installing from branch

---

.github/workflows/infection.yml

Add infection workflow

---

.github/workflows/bc.yml
.github/workflows/codeception.yml
.github/workflows/composer-require-checker.yml
.github/workflows/phpbench.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/rector.yml
.github/workflows/roave-infection.yml

[Docs](https://github.com/shivammathur/setup-php?tab=readme-ov-file#wrench-tools-support): "The latest stable version of composer is set up by default. "

Remove composer tool from configurations

---

.github/workflows/phpstan.yml

Add PHPStan workflow

---

.github/workflows/rector.yml

See https://github.com/rectorphp/rector-src/pull/6747

Set output format for Rector

---

.github/workflows/codeception.yml

Add CodeCov token to Codeception workflow

---

install-packages/install-package/action.yml

| Fixed issues  | 
Related with https://github.com/yiisoft/active-record/actions/runs/14925048201/job/41927897898?pr=420

Quote branch name in command

---

install-packages/install-package/action.yml

| Fixed issues  | 
Related with https://github.com/yiisoft/active-record/actions/runs/14925048201/job/41931085899?pr=420

Add `--exit-code` option

---

install-packages/action.yml
install-packages/install-package/action.yml

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Fixed issues  |

Recognize fork prefix

---

install-packages/install-package/action.yml

Fix to install packages on rector tests
